apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: staging-guestbook-ui
  namepsace: staging
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: staging-guestbook-ui
  template:
    metadata:
      labels:
        app: staging-guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
