apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onsd/ArgoCD_test.git
    targetRevision: v1.1
    path: production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
