apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onsd/ArgoCD_test.git
    targetRevision: v2.1
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  kustomize:
    namePrefix: prod-
